wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1643355922
    t:
      1:
      - 2
      - 3
      4: 3.7.4
      5: 0.12.9
      8:
      - 3
      - 5
